
# Database Configuration
# PostgreSQL connection settings

db.url = jdbc:postgresql://dpg-d6vaj5tm5p6s73a83lbg-a.singapore-postgres.render.com:5432/defalutdb
db.user = saveun
db.password = 7m9I4m2TuPie8mxt8U5uF1gLNrqAkfGA